/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthenticatedAnalyzeRouteImport } from './routes/_authenticated/analyze'
import { Route as AuthenticatedCreditsRouteImport } from './routes/_authenticated/credits'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedAnalysisIdRouteImport } from './routes/_authenticated/analysis.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAnalyzeRoute = AuthenticatedAnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCreditsRoute = AuthenticatedCreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalysisIdRoute = AuthenticatedAnalysisIdRouteImport.update({
  id: '/analysis/$id',
  path: '/analysis/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/analyze': typeof AuthenticatedAnalyzeRoute
  '/credits': typeof AuthenticatedCreditsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/analysis/$id': typeof AuthenticatedAnalysisIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/analyze': typeof AuthenticatedAnalyzeRoute
  '/credits': typeof AuthenticatedCreditsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/analysis/$id': typeof AuthenticatedAnalysisIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/analyze': typeof AuthenticatedAnalyzeRoute
  '/_authenticated/credits': typeof AuthenticatedCreditsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/analysis/$id': typeof AuthenticatedAnalysisIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/analyze'
    | '/credits'
    | '/dashboard'
    | '/history'
    | '/analysis/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/analyze'
    | '/credits'
    | '/dashboard'
    | '/history'
    | '/analysis/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/analyze'
    | '/_authenticated/credits'
    | '/_authenticated/dashboard'
    | '/_authenticated/history'
    | '/_authenticated/analysis/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/analyze': {
      id: '/_authenticated/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AuthenticatedAnalyzeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/credits': {
      id: '/_authenticated/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof AuthenticatedCreditsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analysis/$id': {
      id: '/_authenticated/analysis/$id'
      path: '/analysis/$id'
      fullPath: '/analysis/$id'
      preLoaderRoute: typeof AuthenticatedAnalysisIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalyzeRoute: typeof AuthenticatedAnalyzeRoute
  AuthenticatedCreditsRoute: typeof AuthenticatedCreditsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedAnalysisIdRoute: typeof AuthenticatedAnalysisIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalyzeRoute: AuthenticatedAnalyzeRoute,
  AuthenticatedCreditsRoute: AuthenticatedCreditsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedAnalysisIdRoute: AuthenticatedAnalysisIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
